name: Main Workflow
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  select-environment:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: systest
      app_name: myApp
    secrets:
      SYSTEST_IPS: ${{ secrets.SYSTEST_IPS }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
